services:
  builder:
    build:
      context: .
    privileged: true
    volumes:
      - /dev:/dev
      - .:/root/qmk-builder
      - ./keymap:/root/qmk_firmware/keyboards/planck/keymaps/desheffer
    tty: true
