services:
  builder:
    extends:
      file: ../common/docker-compose.yml
      service: builder
    build:
      args:
        QMK_TAG: 0.17.0
    volumes:
      - ./keymap:/root/qmk_firmware/keyboards/planck/keymaps/desheffer
