#pragma once

#define TAPPING_TERM 120

#ifdef AUDIO_ENABLE
#    define STARTUP_SONG SONG(PLANCK_SOUND)

#    define DEFAULT_LAYER_SONGS { SONG(COLEMAK_SOUND), SONG(QWERTY_SOUND) }
#endif

#define MIDI_BASIC

#define RGBLIGHT_EFFECT_RAINBOW_MOOD
